SELECT IDINMUEBLE
FROM (SELECT INM.ID AS IDINMUEBLE, COUNT(*) AS CNT
	FROM INMUEBLE INM
	INNER JOIN OFRECESERVICIO OFR ON INM.ID=OFR.IDINMUEBLE
	WHERE INM.DISPONIBLE = 1
		AND (OFR.IDSERVICIOMENAJE = '' OR OFR.IDSERVICIOMENAJE = '')
		AND NOT EXISTS (SELECT *
				FROM RESERVA RES
				WHERE RES.IDINMUEBLE = INM.ID
				AND (RES.FECHAINICIO IN ('', '') OR RES.FECHAFIN IN ('','')))
	GROUP BY INM.ID)
WHERE CNT = 2;
