-- DOCUMENTO CON ESCENARIOS DE PRUBEAS 

ALTER SESSION SET NLS_DATE_LANGUAGE = 'AMERICAN'

--PRUEBAS OPERADOR

-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA MISMA PK *saca error
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBA2USUARIO@PRUEBA.COM', '1111111');
-- TUPLE MISMO EMAIL *saca error
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (102, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;


-- PRUEBAS USUARIO

-- TUPLA NUEVA
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, TELEFONO, TIPO) VALUES (101, 'PRUEBAUSUARIO', 'PRUEBAUSUARIO@PRUEBA.COM', '11111111', 'Estudiante');
-- TUPLA MISMA PK *saca error
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, TELEFONO, TIPO) VALUES (101, 'PRUEBAUSUARIO', 'PRUEBA2USUARIO@PRUEBA.COM', '11111111', 'Estudiante');
-- TUPLE MISMO EMAIL *saca error
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, TELEFONO, TIPO) VALUES (102, 'PRUEBAUSUARIO', 'PRUEBAUSUARIO@PRUEBA.COM', '11111111', 'Estudiante');
-- TUPLE CKUSUARIOTIPO *saca error
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, TELEFONO, TIPO) VALUES (103, 'PRUEBAUSUARIO', 'PRUEBA3USUARIO@PRUEBA.COM', '11111111', 'estudiante');
-- DELETE TUPLE
DELETE FROM USUARIO WHERE ID=101;


-- PRUEBA PERSONA JURIDICA

-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (102, 'PRUEBA', 'PRUEBAUSUARIO2@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, 1, NULL, 'Hotel');
-- TUPLA MISMA PK *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111112, 1111112, 1, NULL, 'Hotel');
-- TUPLE MISMO IDSUPERINTENDENCIATURISMOL *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (102, 1111111, 1111112, 1, NULL, 'Hotel');
-- TUPLE MISMO IDCAMARA COMERCIO *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (102, 1111112, 1111111, 1, NULL, 'Hotel');
-- TUPLE CKPERSONAJURIDICATIPO *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (102, 1111112, 1111112, 1, NULL, 'hotel');
-- TUPLE CKPRECIONOCHE *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (102, 1111112, 1111112, 1, -100, 'Hostal');
-- TUPLE FK FALSA *saca error
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (103, 1111112, 1111112, 1, NULL, 'Hotel');
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 102;

-- PRUEBA PERSONA NATURAL

-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLA MISMA PK *saca error
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLE CKUPERSONANATURALTIPO *saca error
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'vecino');
-- TUPLE FK FALSA *saca error
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (102, 'Vecino');
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;


-- PRUEBA HORARIO

-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, NULL, 1, 'Hostal');
-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (102, 'PRUEBA', 'PRUEBAUSUARIO2@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (102, 1111112, 1111112, NULL, 1, 'Hostal');
-- TUPLA NUEVA
INSERT INTO HORARIO (IDHOSTAL, DIA, HORAABRE, HORACIERRA) VALUES (101, 'L', 1, 2);
-- TUPLA MISMA PK *saca error
INSERT INTO HORARIO (IDHOSTAL, DIA, HORAABRE, HORACIERRA) VALUES (101, 'L', 1, 2);
-- TUPLE CKHORAABRE *saca error
INSERT INTO HORARIO (IDHOSTAL, DIA, HORAABRE, HORACIERRA) VALUES (102, 'L', 24, 11);
-- TUPLE FK CKHORACIERRE *saca error
INSERT INTO HORARIO (IDHOSTAL, DIA, HORAABRE, HORACIERRA) VALUES (102, 'L', 10, 24);
-- TUPLE FK FALSA *saca error
INSERT INTO HORARIO (IDHOSTAL, DIA, HORAABRE, HORACIERRA) VALUES (103, 'L', 10, 23);
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 102;

-- PRUEBA INMUEBLE

-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Vivienda', 3, 1, NULL);
-- TUPLA MISMA PK *saca error
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Vivienda', 3, 1, NULL);
-- TUPLE CKTIPOINMUEBLE saca error
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'vivienda', 3, 1, NULL);
-- TUPLE CKCAPACIDAD *saca error
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Vivienda', -1, 1, NULL);
-- TUPLE CKDISPONIBLE *saca error
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Vivienda', -1, 2, NULL);
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;

-- PRUEBA HABITACION HOTEL

-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, 5, NULL, 'Hotel');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Hotel', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (102, 'PRUEBA', 'Habitacion Hotel', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (101, 101, 1, 'Estandar', 1, 5, 'PRUEBA');
-- TUPLA FK FALSE INMUEBLE *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (103, 101, 1, 'Estandar', 1, 5, 'PRUEBA');
-- TUPLA FK FALSE PERSONA JURIDICA *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (102, 102, 1, 'Estandar', 1, 5, 'PRUEBA');
-- TUPLA MISMA PK *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (101, 101, 1, 'Estandar', 1, 5, 'PRUEBA');
-- TUPLA MISMA CKTIPOHABITACIONHOTEL *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (102, 101, 1, 'estandar', 1, 5, 'PRUEBA');
-- TUPLA MISMA CKTIPOHABITACIONHOTEL *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (102, 101, 1, 'Estandar', -1, 5, 'PRUEBA');
-- TUPLA MISMA CKTIPOHABITACIONHOTEL *saca error
INSERT INTO HABITACIONHOTEL (ID, IDHOTEL, NUMERO, TIPO, PRECIONOCHE, TAMANHO, UBICACION) VALUES (102, 101, 1, 'Estandar', 1, -5, 'PRUEBA');
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 102;


-- PRUEBA HABITACION HOSTAL
-- TUPLA NUEVA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, NULL, 1, 'Hostal');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Hostal', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO habitacionhostal (ID, idhostal, numero) VALUES (101, 101, 1);
-- TUPLA MISMA PK *saca error
INSERT INTO habitacionhostal (ID, idhostal, numero) VALUES (101, 101, 1);
-- TUPLA MISMA FK Falsa *saca error
INSERT INTO habitacionhostal (ID, idhostal, numero) VALUES (102, 101, 1);
-- TUPLA MISMA FK Falsa *saca error
INSERT INTO habitacionhostal (ID, idhostal, numero) VALUES (101, 102, 1);
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;



-- Prueba Habitacion vivienda

INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, NULL, 1, 'Hostal');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, 3387, 1587, 151, 'Horred', 1);
-- TUPLA MISMA PK *SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, 3387, 1587, 151, 'Horred', 1);
-- TUPLA FK A INMUEBLE FALSA *SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (102, 101, 1, 3387, 1587, 151, 'Horred', 1);
-- TUPLA FK A PERSONA JURIDICA FALSA * SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 102, 1, 3387, 1587, 151, 'Horred', 1);
-- TUPLA CK NUMERO SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, -1, 3387, 1587, 151, 'Horred', 1);
-- TUPLA CK PRECIO SEMESTRE SCA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, -1, 1587, 151, 'Horred', 1);
-- TUPLA CK PRECIO MES SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, 3387, -1, 151, 'Horred', 1);
-- TUPLA CK PRECIA NOCHE SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, 3387, 1587, -1, 'Horred', 1);
-- TUPLA CK INDIVIDUAL SACA ERROR
INSERT INTO HABITACIONVIVIENDA (ID, IDVIVIENDA, NUMERO, PRECIOSEMESTRE, PRECIOMES, PRECIONOCHE, UBICACION, INDIVIDUAL) VALUES (101, 101, 1, 3387, 1587, 151, 'Horred', 2);
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;


-- PRUEBA SERVICIO MENAJE

--TUPLA NUEVA
INSERT INTO SERVICIOMENAJE (NOMBRE, TIPO) VALUES ('Cucharas', 'Menaje');
-- TUPLA CON MISMA PK SACA ERROR
INSERT INTO SERVICIOMENAJE (NOMBRE, TIPO) VALUES ('Cucharas', 'Menaje');
--TUPLA CK TIPO SACA ERROR
INSERT INTO SERVICIOMENAJE (NOMBRE, TIPO) VALUES ('Cuchillo', 'Otro Tipo');
-- TUPLA CK NOT NULL TIPO SACA ERROR
INSERT INTO SERVICIOMENAJE (NOMBRE, TIPO) VALUES ('Cuchillo', NULL);
-- BORRAR
DELETE FROM SERVICIOMENAJE WHERE NOMBRE='Cucharas';

-- PRUEBA OFRECE SERVICIO
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO SERVICIOMENAJE (NOMBRE, TIPO) VALUES ('Cucharas', 'Menaje');
-- TUPLA NUEVA
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Cucharas', 101, NULL, 10);  
-- TUPLA MISMA PK SACA ERROR
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Cucharas', 101, NULL, 10); 
-- TUPLA FK A SERVICIO MENAJE SACA ERROR
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Silla', 101, NULL, 10);
-- TUPLA FK A INMUEBLE SACA ERROR
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Cucharas', 102, NULL, 10);  
-- TUPLA CK COSTO>0 SACA ERROR
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Cucharas', 101, -1, 10);  
-- TUPLA CK CANTIDAD >0 SACA ERROR
INSERT INTO OFRECESERVICIO (IDSERVICIOMENAJE, IDINMUEBLE, COSTO, CANTIDAD) VALUES ('Cucharas', 101, NULL, -1);  

-- DELETE TUPLE
DELETE FROM SERVICIOMENAJE WHERE NOMBRE='Cucharas';
-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;


-- Prueba reserva
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- TUPLA NUEVA
INSERT INTO PERSONAJURIDICA (ID, idsuperintendenciaturismo, idcamaracomercio, categoria, precionoche, tipo) VALUES (101, 1111111, 1111111, NULL, 1, 'Hostal');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, TELEFONO, TIPO) VALUES (101, 'PRUEBAUSUARIO', 'PRUEBAUSUARIO@PRUEBA.COM', '11111111', 'Estudiante');
-- TUPLA NUEVA
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 0, 101,101 , 101, 700000);
-- TUPLA CON MISMO PK
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 0, 101,101 , 101, 700000);
-- TUPLA CON FK IDINMUEBLE FALSA SACA ERROR
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 0, 101,101 , 102, 700000);
-- TUPLA CON FK OPERADOR FALSA SACA ERROR
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 0, 102,101 , 101, 700000);
-- TUPLA CON FK USUARIO FALSA SACA ERROR
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 0, 101,102 , 101, 700000);
-- TUPLA CK ESTADO SACA ERROR
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '01/02/21', 700000, '29/12/20', 0, 9, 2, 101,101 , 101, 700000);
-- TUPLA FECHAS SACA ERROR
INSERT INTO
RESERVA(ID, FECHAINICIO, FECHAFIN, VALORTOTAL, FECHACANCELACION, DESCUENTO, CAPACIDAD, ESTADO, IDOPERADOR, IDUSUARIO, IDINMUEBLE, PAGADO)
VALUES 
(1, '01/01/21', '30/12/20', 700000, '29/12/20', 0, 9, 0, 101,101 , 101, 700000);

-- DELETE TUPLE
DELETE FROM INMUEBLE WHERE ID = 101;
-- DELETE TUPLE
DELETE FROM OPERADOR WHERE ID = 101;
--
DELETE FROM USUARIO WHERE ID=101;

-- PRUEBA PERSONA NATURAL
--NUEVA TUPLA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
-- NUEVA TUPLA
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- NUEVA TUPLA CON MISMO PK SACA ERROR
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLA CON FK MAL SACA ERROR
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (102, 'Vecino');
-- TUPLA CON CHEK TIPO MAL SACA ERROR
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'VecinoSSS');

--BORRAR COSAS
DELETE FROM OPERADOR WHERE ID = 101;



--PRUEBA DE HABITACION
--NUEVA TUPLA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
--NUEVA TUPLA
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- nueva tupla
INSERT INTO HABITACION (ID, TAMANHO, PRECIOMES, IDPERSONA) VALUES (101, 4169, 1410, 101);
-- MISMO PK SACA ERROR
INSERT INTO HABITACION (ID, TAMANHO, PRECIOMES, IDPERSONA) VALUES (101, 4169, 1410, 101);
-- fk inmueble saca error
INSERT INTO HABITACION (ID, TAMANHO, PRECIOMES, IDPERSONA) VALUES (102, 4169, 1410, 101);
-- FK PERSONA SACA ERROR
INSERT INTO HABITACION (ID, TAMANHO, PRECIOMES, IDPERSONA) VALUES (101, 4169, 1410, 102);

--DELETE

DELETE FROM OPERADOR WHERE ID = 101;
DELETE FROM INMUEBLE WHERE ID = 101;





-- PRUEBA VIVIENDA
--NUEVA TUPLA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
--NUEVA TUPLA
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO VIVIENDA (ID, NUMEROHABITACIONES, COSTONOCHE, DIASUTILIZADO, IDPERSONA) VALUES (101, 1, 800, 1, 101);
-- TUPLA CON MISMA  PK SACA ERROR
INSERT INTO VIVIENDA (ID, NUMEROHABITACIONES, COSTONOCHE, DIASUTILIZADO, IDPERSONA) VALUES (101, 1, 800, 1, 101);
-- TUPLA FK INMUEBLE SACA ERROR
INSERT INTO VIVIENDA (ID, NUMEROHABITACIONES, COSTONOCHE, DIASUTILIZADO, IDPERSONA) VALUES (102, 1, 800, 1, 101);
-- TUPLA FK PERSONA SACA ERROR
INSERT INTO VIVIENDA (ID, NUMEROHABITACIONES, COSTONOCHE, DIASUTILIZADO, IDPERSONA) VALUES (101, 1, 800, 1, 102);
--DELETE
DELETE FROM OPERADOR WHERE ID = 101;
DELETE FROM INMUEBLE WHERE ID = 101;


-- PRUEBA APARTAMENTO
--NUEVA TUPLA
INSERT INTO OPERADOR (ID, NOMBRE, EMAIL, TELEFONO) VALUES (101, 'PRUEBA', 'PRUEBAUSUARIO@PRUEBA.COM', '1111111');
--NUEVA TUPLA
INSERT INTO PERSONANATURAL (ID, TIPO) VALUES (101, 'Vecino');
-- TUPLA NUEVA
INSERT INTO INMUEBLE (ID, DIRECCION, TIPO, CAPACIDAD, DISPONIBLE, FECHARESERVAFINAL) VALUES (101, 'PRUEBA', 'Habitacion Vivienda', 3, 1, NULL);
-- TUPLA NUEVA
INSERT INTO APARTAMENTO (ID, AMOBLADO, PRECIOMES, IDPERSONA) VALUES (101, 0, 1105, 101);
-- TUPLA NUEVA MISMA PK SACA ERROR
INSERT INTO APARTAMENTO (ID, AMOBLADO, PRECIOMES, IDPERSONA) VALUES (101, 0, 1105, 101);
-- TUPLA FK INMUEBLE SACA ERROR
INSERT INTO APARTAMENTO (ID, AMOBLADO, PRECIOMES, IDPERSONA) VALUES (102, 0, 1105, 101);
-- TUPLA FK PERSONA SACA ERROR
INSERT INTO APARTAMENTO (ID, AMOBLADO, PRECIOMES, IDPERSONA) VALUES (101, 0, 1105, 102);
-- TUPLA CH AMOBLADO SACA ERRROR
INSERT INTO APARTAMENTO (ID, AMOBLADO, PRECIOMES, IDPERSONA) VALUES (101, 2, 1105, 101);
DELETE FROM OPERADOR WHERE ID = 101;
DELETE FROM INMUEBLE WHERE ID = 101;

