DROP TABLE "OPERADOR" CASCADE CONSTRAINTS;
DROP TABLE "USUARIO" CASCADE CONSTRAINTS;
DROP TABLE "PERSONAJURIDICA" CASCADE CONSTRAINTS;
DROP TABLE "HORARIO" CASCADE CONSTRAINTS;
DROP TABLE "INMUEBLE" CASCADE CONSTRAINTS;
DROP TABLE "HABITACIONHOTEL" CASCADE CONSTRAINTS;
DROP TABLE "HABITACIONVIVIENDA" CASCADE CONSTRAINTS;
DROP TABLE "HABITACIONHOSTAL" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOMENAJE" CASCADE CONSTRAINTS;
DROP TABLE "OFRECESERVICIO" CASCADE CONSTRAINTS;
DROP TABLE "RESERVA" CASCADE CONSTRAINTS;
DROP TABLE "PERSONANATURAL" CASCADE CONSTRAINTS;
DROP TABLE "HABITACION" CASCADE CONSTRAINTS;
DROP TABLE "VIVIENDA" CASCADE CONSTRAINTS;
DROP TABLE "APARTAMENTO" CASCADE CONSTRAINTS;
DROP SEQUENCE "INMUEBLE_SEQUENCE";
DROP SEQUENCE "OPERADOR_SEQUENCE";
DROP SEQUENCE "RESERVA_SEQUENCE";
DROP SEQUENCE "USUARIO_SEQUENCE";
DROP SEQUENCE "RESERVA_COLECTIVA_SEQUENCE";


-- Eliminar el contenido de todas las tablas de la base de datos
-- El orden es importante. Por qu�?
DELETE FROM OPERADOR;
DELETE FROM USUARIO;
DELETE FROM PERSONAJURIDICA;
DELETE FROM HORARIO;
DELETE FROM INMUEBLE;
DELETE FROM HABITACIONHOTEL;
DELETE FROM HABITACIONVIVIENDA;
DELETE FROM HABITACIONHOSTAL;
DELETE FROM SERVICIOMENAJE;
DELETE FROM OFRECESERVICIO;
DELETE FROM RESERVA;
DELETE FROM PERSONANATURAL;
DELETE FROM HABITACION;
DELETE FROM VIVIENDA;
DELETE FROM APARTAMENTO;
