SELECT IDINMUEBLE 
	FROM (SELECT INM.ID AS IDINMUEBLE, COUNT(*) AS CNT  
		FROM VIVIENDA VIV
		INNER JOIN INMUEBLE INM ON INM.ID=VIV.ID
		INNER JOIN OFRECESERVICIO OFR ON INM.ID=OFR.IDINMUEBLE 
		WHERE INM.DISPONIBLE = 1 "  
		AND NOT EXISTS (SELECT * 
				FROM RESERVA RES 
				WHERE RES.IDINMUEBLE = INM.ID 
				AND (RES.FECHAINICIO BETWEEN ? AND ? OR RES.FECHAFIN BETWEEN ? AND ? )) 
				AND INM.CAPACIDAD >= ? 
				AND VIV.DIASUTILIZADO<=30
				GROUP BY INM.ID) 
				"WHERE CNT =  ?

