SELECT INMUEBLE.*, SEMANA
FROM 
(SELECT INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY') AS SEMANA, AVG(RESERVA.CAPACIDAD/INMUEBLE.CAPACIDAD) AS TASAOCUPACION
FROM INMUEBLE
INNER JOIN RESERVA ON RESERVA.IDINMUEBLE = INMUEBLE.ID
GROUP BY INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')) X
INNER JOIN INMUEBLE ON INMUEBLE.ID =X.ID
WHERE (SEMANA, TASAOCUPACION) IN (SELECT SEMANA, MAX(TASAOCUPACION)
FROM
(SELECT INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY') AS SEMANA, AVG(RESERVA.CAPACIDAD/INMUEBLE.CAPACIDAD) AS TASAOCUPACION
FROM INMUEBLE
INNER JOIN RESERVA ON RESERVA.IDINMUEBLE = INMUEBLE.ID
GROUP BY INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY'))
GROUP BY SEMANA);

SELECT INMUEBLE.*, SEMANA
FROM (SELECT INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY') AS SEMANA, AVG(RESERVA.CAPACIDAD/INMUEBLE.CAPACIDAD) AS TASAOCUPACION
FROM INMUEBLE
INNER JOIN RESERVA ON RESERVA.IDINMUEBLE = INMUEBLE.ID
GROUP BY INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')) X
INNER JOIN INMUEBLE ON X.ID = INMUEBLE.ID
WHERE (SEMANA, TASAOCUPACION) IN (SELECT SEMANA, MIN(TASAOCUPACION)
FROM
(SELECT INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY') AS SEMANA, AVG(RESERVA.CAPACIDAD/INMUEBLE.CAPACIDAD) AS TASAOCUPACION
FROM INMUEBLE
INNER JOIN RESERVA ON RESERVA.IDINMUEBLE = INMUEBLE.ID
GROUP BY INMUEBLE.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY'))
GROUP BY SEMANA);


SELECT OPERADOR.*, SEMANA
FROM (SELECT OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')AS SEMANA, COUNT(*) AS C
FROM OPERADOR
INNER JOIN RESERVA ON OPERADOR.ID = RESERVA.IDOPERADOR
GROUP BY OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')) X
INNER JOIN OPERADOR ON OPERADOR.ID = X.ID
WHERE (SEMANA, C) IN (SELECT SEMANA, MAX(C)
FROM
(SELECT OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')AS SEMANA, COUNT(*) AS C
FROM OPERADOR
INNER JOIN RESERVA ON OPERADOR.ID = RESERVA.IDOPERADOR
GROUP BY OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY'))
GROUP BY SEMANA);


SELECT OPERADOR.*, SEMANA
FROM (SELECT OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')AS SEMANA, COUNT(*) AS C
FROM OPERADOR
INNER JOIN RESERVA ON OPERADOR.ID = RESERVA.IDOPERADOR
GROUP BY OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')) X
INNER JOIN OPERADOR ON OPERADOR.ID = X.ID
WHERE (SEMANA, C) IN (SELECT SEMANA, MIN(C)
FROM
(SELECT OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY')AS SEMANA, COUNT(*) AS C
FROM OPERADOR
INNER JOIN RESERVA ON OPERADOR.ID = RESERVA.IDOPERADOR
GROUP BY OPERADOR.ID, TRUNC(RESERVA.FECHAINICIO, 'DAY'))
GROUP BY SEMANA);