SELECT *
FROM USUARIO 
WHERE USUARIO.ID NOT IN (
SELECT USUARIO.ID
FROM USUARIO
INNER JOIN RESERVA ON USUARIO.ID = RESERVA.IDUSUARIO
WHERE IDINMUEBLE = 1? AND FECHAINICIO BETWEEN 2? AND 3? AND FECHAFIN BETWEEN 2? AND 3?
GROUP BY USUARIO.ID);